//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurePFX.Application.Exceptions.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SrcMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SrcMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecurePFX.Application.Exceptions.Resource.SrcMsg", typeof(SrcMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo do certificado é obrigatório.
        /// </summary>
        public static string SRC001 {
            get {
                return ResourceManager.GetString("SRC001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contexto inválido.
        /// </summary>
        public static string SRC002 {
            get {
                return ResourceManager.GetString("SRC002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria inválida.
        /// </summary>
        public static string SRC003 {
            get {
                return ResourceManager.GetString("SRC003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo IsActive é obrigatório.
        /// </summary>
        public static string SRC004 {
            get {
                return ResourceManager.GetString("SRC004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas arquivos .pfx são aceitos.
        /// </summary>
        public static string SRC005 {
            get {
                return ResourceManager.GetString("SRC005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho máximo do arquivo não pode exceder: 5mb.
        /// </summary>
        public static string SRC006 {
            get {
                return ResourceManager.GetString("SRC006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificado inválido ou senha incorreta.
        /// </summary>
        public static string SRC007 {
            get {
                return ResourceManager.GetString("SRC007", resourceCulture);
            }
        }
    }
}
